# Generated by Django 3.0.2 on 2020-01-08 00:45

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_userprofile_CREATE_USER', to='api.UserProfile')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Organization')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_userprofile_UPDATE_USER', to='api.UserProfile')),
            ],
            options={
                'db_table': 'user',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.AddField(
            model_name='organization',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_organization_CREATE_USER', to='api.UserProfile'),
        ),
        migrations.AddField(
            model_name='organization',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_organization_UPDATE_USER', to='api.UserProfile'),
        ),
        migrations.CreateModel(
            name='UserCreationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('keycloak_email', models.EmailField(max_length=254)),
                ('external_username', models.CharField(blank=True, max_length=150, null=True)),
                ('is_mapped', models.BooleanField(default=False)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_usercreationrequest_CREATE_USER', to='api.UserProfile')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_usercreationrequest_UPDATE_USER', to='api.UserProfile')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='creation_request', to='api.UserProfile')),
            ],
            options={
                'db_table': 'user_creation_request',
                'unique_together': {('keycloak_email', 'external_username')},
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
